### ISSUE TITLE
Restore partial skipping in Intro cutscene

### ISSUE THREAD

**Issue by Tomasak** [Sergeanur/SCFIX-Miami#1]
On PS2 it's possible to skip only parts of intro cutscene to each part - i.e. from Sonny to Airport, from Airport to Deal etc.

**Comment by Sergeanur** [comment]
What? How?

**Comment by Tomasak** [comment]
Hmm, i remember it incorrectly.
If you use PS2 main.scm on PC, then Attack and Jump buttons skip the cutscene partially, while using Run button skips the cutscene to arriving at Ken Rosenberg's office

**Comment by Sergeanur** [comment]
Yeah but that wasn't the intended behavior now, was it? For what it's worth you can still skip individual cutscenes by holding Shift since the loading screen and pressing Space or LMB to skip.

**Comment by Tomasak** [comment]
Oh interesting, closing this then.
